link :	vettore.o main.o utils.o 
	gcc  vettore.o main.o utils.o -o vettore.exe
	
vettore.o :
	gcc -c vettore.c
	
main.o :
	gcc -c main.c
	
utils.o :
	gcc -c utils.c
	
clean : 
	rm -f *.o *.exe